// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Uni.LectureTheatres.DataAccess;

namespace Uni.LectureTheatres.DataAccess.Migrations
{
    [DbContext(typeof(LectureTheatreDbContext))]
    partial class LectureTheatreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Uni.LectureTheatres.Domain.LectureTheatre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LectureTheatres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0668573-0717-4b47-97cf-3842ff4b17ad"),
                            Capacity = 100,
                            Name = "Room15_Test"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
